// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gotodo

type NewTodo struct {
	Titulo string `json:"titulo"`
	Text   string `json:"text"`
	DtTodo string `json:"dtTodo"`
	UserID int    `json:"userId"`
}

type Usuario struct {
	ID   int    `json:"id"`
	Nome string `json:"nome"`
}
